# Custom Language File for Launcher Customizer

[ejs.app]
title = "N.O.E. Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Thermidoren/DalthianLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher de N.O.E.!"
welcomeDescription = "C'est votre dernière sauvegarde!"
welcomeDescCTA = "Initialisation des données de la simulation."
