# Custom Language File for Launcher Customizer

[ejs.app]
title = "Lyterra Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Thermidoren/DalthianLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher de Lyterra!"
welcomeDescription = "Vous vous apprêtez à fouler la terre des dieux..."
welcomeDescCTA = "Que la meilleure colonie l'emporte."
