# Custom Language File for Launcher Customizer

[ejs.app]
title = "Dalthian Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Thermidoren/DalthianLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/dalthian"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher de DalthianRP!"
welcomeDescription = "Vous voici aux portes d'un vaste monde de roleplay médiéval Dark Fantasy!"
welcomeDescCTA = "Encore un peu de patience, vous foulerez bientôt ces terres de vos pieds."
